### ISSUE TITLE
dbus setup error

### ISSUE THREAD

**Issue by krishnahemanth** [HoneyPots0/HPomb#3]
installing requirements fails and exits code 1.

**To Reproduce**
pip3 install -r requirements.txt

**Expected behavior**
ERROR: Command errored out with exit status 1:
     command: 'c:\users\krishna hemanth\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Krishna Hemanth\\AppData\\Local\\Temp\\pip-install-dmazxakj\\dbus-python\\setup.py'"'"'; __file__='"'"'C:\\Users\\Krishna Hemanth\\AppData\\Local\\Temp\\pip-install-dmazxakj\\dbus-python\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Krishna Hemanth\AppData\Local\Temp\pip-record-n3se9bmw\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\krishna hemanth\appdata\local\programs\python\python38-32\Include\dbus-python'
         cwd: C:\Users\Krishna Hemanth\AppData\Local\Temp\pip-install-dmazxakj\dbus-python\
    Complete output (5 lines):
    running install
    running build
    creating C:\Users\Krishna Hemanth\AppData\Local\Temp\pip-install-dmazxakj\dbus-python\build
    creating C:\Users\Krishna Hemanth\AppData\Local\Temp\pip-install-dmazxakj\dbus-python\build\temp.win32-3.8
    error: [WinError 193] %1 is not a valid Win32 application
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\krishna hemanth\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Krishna Hemanth\\AppData\\Local\\Temp\\pip-install-dmazxakj\\dbus-python\\setup.py'"'"'; __file__='"'"'C:\\Users\\Krishna Hemanth\\AppData\\Local\\Temp\\pip-install-dmazxakj\\dbus-python\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Krishna Hemanth\AppData\Local\Temp\pip-record-n3se9bmw\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\krishna hemanth\appdata\local\programs\python\python38-32\Include\dbus-python' Check the logs for full command output.

**Screenshots**

![image](https://user-images.githubusercontent.com/47827892/92516633-1eab0600-f233-11ea-86d3-a8394e5cbc75.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Comment by Flyingzaptop** [comment]
Same with Linux

**Comment by HoneyPots0** [comment]
i fixed the problem please reinstall

**Comment by krishnahemanth** [comment]
The problem still persists exit status 1. Maybe still dbus setup error.

**Comment by HoneyPots0** [comment]
bro please uninstall old git 
and git new repo for new updates 
thank you

**Comment by krishnahemanth** [comment]
Am on termux can u please say the process for unistall? Im an newb so please 😅

**Comment by HoneyPots0** [comment]
not a problem dear 
just type where you git Tool
**rm -rf HPomb**

For install 
**git clone https://github.com/HoneyPots0/HPomb.git**

**Comment by HoneyPots0** [comment]
my instagram id : honeypots0
